### ISSUE TITLE
Feature request: Router restart, reconnect and firmware version

### ISSUE THREAD

**Issue by myhomeiot** [chemelli74/aiovodafone#7]
Thanks for great job! This was in my wishlist and I'm very happy to see Home Assistant integration (based on this library).
As you already did most of the work, please think to implement router restart (maybe reconnect and some basic information as firmware version).
Most of the users has dynamic IP, so restart/reconnect  very useful then user want to change external IP.
Firmware version useful because sometimes Vodafone update it and if user monitor it and start getting the problems at least he can know the possible source :-)

**Comment by chemelli74** [comment]
HI @myhomeiot,

I'm for sure going to add more sensors.
I started with device tracker because the old custom integration was providing such functionality and for new HA official integration you need to start with only 1 domain at a time.

Which model are you using ? I would like to keep track of all working in the readme (you may be so kind to provide a PR to update the file).

Simone

**Comment by myhomeiot** [comment]
Excellent! I will make tests with HA 2023.9 and lets you know.

**Comment by chemelli74** [comment]
Features added to v0.0.9 of the library.
Please test and report back.

Simone

**Comment by myhomeiot** [comment]
@chemelli74 Tested, working with Vodafone Sercomm H300S
